name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/$GITHUB_REPOSITORY:$GITHUB_SHA

    - name: Tag image latest
      run: docker tag ${{ env.REGISTRY }}/$GITHUB_REPOSITORY:$GITHUB_SHA ${{ env.REGISTRY }}/$GITHUB_REPOSITORY:latest

    - name: Push the Docker image to registry (SHA tagged)
      run: docker push ${{ env.REGISTRY }}/$GITHUB_REPOSITORY:$GITHUB_SHA

    - name: Push the Docker image to registry (latest)
      run: docker push ${{ env.REGISTRY }}/$GITHUB_REPOSITORY:$GITHUB_SHA
